# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE1: baldwin_cortes_resume
      FILE2: baldwin_cortes_resume_pubs
      FILE3: baldwin_cortes_resume_pv_research
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: resume build
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE1 }}
          working_directory: ${{ env.DIR }}
      - name: resume move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE1 }}.pdf ./github_artifacts/
      - name: Upload resume pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE1 }}.pdf
          path: ./github_artifacts
      - name: resume pubs build
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE2 }}
          working_directory: ${{ env.DIR }}
      - name: resume pubs move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE2 }}.pdf ./github_artifacts/
      - name: Upload resume pubs pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE2 }}.pdf
          path: ./github_artifacts
      - name: resume pv build
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE3 }}
          working_directory: ${{ env.DIR }}
      - name: resume pubs move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE3 }}.pdf ./github_artifacts/
      - name: Upload resume pubs pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE3 }}.pdf
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: download first artifact
        uses: actions/download-artifact@v3
        with:
          path: github_artifacts
          name: baldwin_cortes_resume.pdf
      - name: download second artifact
        uses: actions/download-artifact@v3
        with:
          path: github_artifacts
          name: baldwin_cortes_resume_pubs.pdf
      - name: download third artifact
        uses: actions/download-artifact@v3
        with:
          path: github_artifacts
          name: baldwin_cortes_resume_pv_research.pdf
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
